EXCLUDED_FIELDS = {
    "Amendement",
    "pk",
    "article_pk",
    "lecture_pk",
    "parent_pk",
    "parent_rectif",
    "subdiv_type",
    "subdiv_titre",
    "subdiv_num",
    "subdiv_mult",
    "subdiv_pos",
    "created_at",
    "modified_at",
    "user_table_pk",
}
