from tasks.app import *  # noqa
from tasks.backup import *  # noqa
from tasks.db import *  # noqa
from tasks.deploy import *  # noqa
from tasks.ovh import *  # noqa
from tasks.monitoring import *  # noqa
from tasks.system import *  # noqa
from tasks.vagrant import *  # noqa
from tasks.web import *  # noqa
